# yamllint disable
name:                taffy-roos
version:             0.1.0.0
git:                 "https://gitlab.com/roosemberth/taffy-roos"
license:             GPL-3.0-or-later
license-file:        COPYING
author:              "Roosembert Palacios"
maintainer:          "roosembert.palacios@gmail.com"
copyright:           "Roosembert Palacios"

data-files:
  taffybar.css

extra-source-files:
- README.md
- COPYING

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Gitlab at <https://gitlab.com/roosemberth/taffy-roos>

library:
  source-dirs: .

dependencies:
- base >= 4.7 && < 5
- taffybar
- text >= 1.2.3
- xdg-basedir >= 0.2.2
- directory >= 1.3.3
- gi-gtk >= 3.0.32

executables:
  taffybar:
    main:                taffybar.hs
    source-dirs:         .
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - taffy-roos
